'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
type View='month'|'week'|'day'|'list'; type Priority='high'|'medium'|'low';
type Task={id:string;title:string;details:string;start:string;end:string;category:string;priority:Priority;done:boolean};
const cats:Record<string,string>={'งาน':'#d89d91','ส่วนตัว':'#aeb49a','นัดหมาย':'#c4a6b8'};
const months=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];
const days=['จ.','อ.','พ.','พฤ.','ศ.','ส.','อา.']; const pad=(n:number)=>String(n).padStart(2,'0');
const input=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
const key=(d:Date)=>input(d).slice(0,10); const same=(a:Date,b:Date)=>key(a)===key(b); const add=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const monday=(d:Date)=>{const x=new Date(d);x.setDate(x.getDate()-(x.getDay()+6)%7);x.setHours(0,0,0,0);return x};
function samples():Task[]{const n=new Date(),at=(o:number,h:number)=>{const d=add(n,o);d.setHours(h,0,0,0);return input(d)};return[
 {id:'a',title:'วางแผนงานประจำสัปดาห์',details:'เลือก 3 เรื่องสำคัญ',start:at(0,9),end:at(0,10),category:'งาน',priority:'high',done:false},
 {id:'b',title:'พักและดูแลตัวเอง',details:'เดินเล่นและพักสายตา',start:at(1,12),end:at(1,13),category:'ส่วนตัว',priority:'low',done:false},
 {id:'c',title:'ประชุมติดตามความคืบหน้า',details:'สรุปสิ่งที่ทำเสร็จ',start:at(2,14),end:at(2,15),category:'นัดหมาย',priority:'medium',done:false}]}
export default function Home(){const[view,setView]=useState<View>('month'),[cursor,setCursor]=useState(new Date()),[tasks,setTasks]=useState<Task[]>([]),[ready,setReady]=useState(false),[editing,setEditing]=useState<Task|null>(null),[hide,setHide]=useState(false);
 useEffect(()=>{const x=localStorage.getItem('slowday-tasks');setTasks(x?JSON.parse(x):samples());setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem('slowday-tasks',JSON.stringify(tasks))},[tasks,ready]);
 const visible=useMemo(()=>tasks.filter(t=>!hide||!t.done).sort((a,b)=>a.start.localeCompare(b.start)),[tasks,hide]); const grid=useMemo(()=>Array.from({length:42},(_,i)=>add(monday(new Date(cursor.getFullYear(),cursor.getMonth(),1)),i)),[cursor]); const week=useMemo(()=>Array.from({length:7},(_,i)=>add(monday(cursor),i)),[cursor]);
 const open=(d=new Date())=>{const s=new Date(d);s.setHours(9,0,0,0);const e=new Date(s);e.setHours(10);setEditing({id:'',title:'',details:'',start:input(s),end:input(e),category:'งาน',priority:'medium',done:false})};
 const save=(t:Task)=>{setTasks(a=>t.id?a.map(x=>x.id===t.id?t:x):[...a,{...t,id:crypto.randomUUID()}]);setEditing(null)}; const move=(n:number)=>setCursor(view==='month'?new Date(cursor.getFullYear(),cursor.getMonth()+n,1):add(cursor,n*(view==='week'?7:1)));
 const drop=(e:React.DragEvent,d:Date)=>{const id=e.dataTransfer.getData('text/task'),t=tasks.find(x=>x.id===id);if(!t)return;const s=new Date(t.start),duration=+new Date(t.end)-+s;s.setFullYear(d.getFullYear(),d.getMonth(),d.getDate());setTasks(a=>a.map(x=>x.id===id?{...x,start:input(s),end:input(new Date(+s+duration))}:x))};
 const heading=view==='month'?`${months[cursor.getMonth()]} ${cursor.getFullYear()+543}`:view==='week'?`${week[0].getDate()}–${week[6].getDate()} ${months[week[6].getMonth()]}`:`${cursor.getDate()} ${months[cursor.getMonth()]} ${cursor.getFullYear()+543}`;const done=tasks.filter(t=>t.done).length;
 return <main><header className="top"><div className="brand"><i>❧</i><div><b>SLOWDAY</b><small>จัดวันของคุณอย่างอ่อนโยน</small></div></div><button className="primary" onClick={()=>open()}><span>＋</span> เพิ่มงานใหม่</button></header><div className="shell">
 <aside className="side"><nav>{([['month','▦','รายเดือน'],['week','▤','รายสัปดาห์'],['day','◷','รายวัน'],['list','☷','รายการงาน']] as const).map(x=><button className={view===x[0]?'active':''} onClick={()=>setView(x[0])} key={x[0]}><span>{x[1]}</span>{x[2]}</button>)}</nav><section><p>หมวดหมู่</p>{Object.entries(cats).map(([c,color])=><div className="cat" key={c}><i style={{background:color}}/>{c}<b>{tasks.filter(t=>t.category===c).length}</b></div>)}</section><blockquote>“ค่อย ๆ ทำทีละอย่าง<br/>คุณทำได้แน่นอน”<span>♡</span></blockquote></aside>
 <section className="work"><div className="head"><div><p>MY PLANNER</p><h1>{heading}</h1><small>โฟกัส วางแผน แล้วค่อย ๆ ทำให้สำเร็จ</small></div><div className="arrows"><button onClick={()=>move(-1)}>‹</button><button onClick={()=>setCursor(new Date())}>วันนี้</button><button onClick={()=>move(1)}>›</button></div></div><div className="toolbar"><div>{(['month','week','day','list'] as View[]).map((v,i)=><button className={view===v?'on':''} onClick={()=>setView(v)} key={v}>{['เดือน','สัปดาห์','วัน','รายการ'][i]}</button>)}</div><label><input type="checkbox" checked={hide} onChange={e=>setHide(e.target.checked)}/> ซ่อนงานที่เสร็จ</label></div>
 {view==='month'&&<div className="calendar"><div className="weekdays">{days.map(x=><span key={x}>{x}</span>)}</div><div className="month">{grid.map(d=><div className={`cell ${d.getMonth()!==cursor.getMonth()?'muted':''} ${same(d,new Date())?'today':''}`} key={key(d)} onDoubleClick={()=>open(d)} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,d)}><b>{d.getDate()}</b>{visible.filter(t=>same(new Date(t.start),d)).slice(0,3).map(t=><Chip key={t.id} task={t} open={()=>setEditing(t)}/>)}</div>)}</div></div>}
 {view==='week'&&<div className="week">{week.map(d=><div className={same(d,new Date())?'today':''} key={key(d)} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,d)}><header><small>{days[(d.getDay()+6)%7]}</small><b>{d.getDate()}</b></header>{visible.filter(t=>same(new Date(t.start),d)).map(t=><Card key={t.id} task={t} open={()=>setEditing(t)}/>)}<button className="add" onClick={()=>open(d)}>＋ เพิ่มงาน</button></div>)}</div>}
 {view==='day'&&<div className="daily"><div className="times">{Array.from({length:12},(_,i)=><span key={i}>{pad(i+7)}:00</span>)}</div><div className="track">{visible.filter(t=>same(new Date(t.start),cursor)).map(t=>{const s=new Date(t.start),e=new Date(t.end),top=(s.getHours()+s.getMinutes()/60-7)*64,height=Math.max(48,(+e-+s)/3600000*64);return <button className="timed" key={t.id} style={{top,height,borderColor:cats[t.category]}} onClick={()=>setEditing(t)}><b>{t.title}</b><small>{pad(s.getHours())}:{pad(s.getMinutes())} – {pad(e.getHours())}:{pad(e.getMinutes())}</small></button>})}</div></div>}
 {view==='list'&&<div className="list">{visible.map(t=><div className={t.done?'row done':'row'} key={t.id}><button className="check" onClick={()=>setTasks(a=>a.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done?'✓':''}</button><i style={{background:cats[t.category]}}/><div><b>{t.title}</b><small>{new Date(t.start).toLocaleDateString('th-TH',{day:'numeric',month:'short'})} · {new Date(t.start).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</small></div><span className={t.priority}>{t.priority==='high'?'สำคัญมาก':t.priority==='medium'?'ปานกลาง':'ไม่เร่ง'}</span><button onClick={()=>setEditing(t)}>•••</button></div>)}</div>}</section>
 <aside className="right"><div className="progress"><div className="ring" style={{'--p':`${tasks.length?done/tasks.length*360:0}deg`} as React.CSSProperties}><span>{tasks.length?Math.round(done/tasks.length*100):0}%</span></div><div><small>ความคืบหน้าวันนี้</small><b>{done} จาก {tasks.length} งาน</b></div></div><h2>งานที่กำลังจะมาถึง ✿</h2>{visible.filter(t=>new Date(t.end)>=new Date()).slice(0,4).map(t=><button className="soon" key={t.id} onClick={()=>setEditing(t)}><i style={{background:cats[t.category]}}/><span><b>{t.title}</b><small>{new Date(t.start).toLocaleDateString('th-TH',{weekday:'short',day:'numeric',month:'short'})}</small></span></button>)}<div className="note">♡<br/><i>ความก้าวหน้า<br/>ไม่ต้องสมบูรณ์แบบ</i></div></aside></div>
 {editing&&<Modal task={editing} close={()=>setEditing(null)} save={save} remove={id=>{setTasks(a=>a.filter(x=>x.id!==id));setEditing(null)}}/>}</main>}
function Chip({task,open}:{task:Task;open:()=>void}){return <button draggable onDragStart={e=>e.dataTransfer.setData('text/task',task.id)} onClick={open} className={task.done?'chip done':'chip'} style={{'--c':cats[task.category]} as React.CSSProperties}><i/>{task.title}</button>}
function Card({task,open}:{task:Task;open:()=>void}){return <button draggable onDragStart={e=>e.dataTransfer.setData('text/task',task.id)} onClick={open} className={task.done?'card done':'card'} style={{borderColor:cats[task.category]}}><small>{new Date(task.start).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</small><b>{task.title}</b></button>}
function Modal({task,save,remove,close}:{task:Task;save:(t:Task)=>void;remove:(id:string)=>void;close:()=>void}){const[d,setD]=useState(task),[err,setErr]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();if(!d.title.trim())return setErr('กรุณาใส่ชื่องาน');if(+new Date(d.end)<=+new Date(d.start))return setErr('เวลาสิ้นสุดต้องอยู่หลังเวลาเริ่ม');save({...d,title:d.title.trim()})};return <div className="back" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal" onSubmit={submit}><button type="button" className="x" onClick={close}>×</button><p>NEW MOMENT</p><h2>{task.id?'แก้ไขงาน':'เพิ่มงานใหม่'}</h2><label>ชื่องาน<input autoFocus value={d.title} onChange={e=>setD({...d,title:e.target.value})} placeholder="วันนี้อยากทำอะไร?"/></label><div className="cols"><label>เริ่มต้น<input type="datetime-local" value={d.start} onChange={e=>setD({...d,start:e.target.value})}/></label><label>สิ้นสุด<input type="datetime-local" value={d.end} onChange={e=>setD({...d,end:e.target.value})}/></label></div><div className="cols"><label>หมวดหมู่<select value={d.category} onChange={e=>setD({...d,category:e.target.value})}>{Object.keys(cats).map(c=><option key={c}>{c}</option>)}</select></label><label>ความสำคัญ<select value={d.priority} onChange={e=>setD({...d,priority:e.target.value as Priority})}><option value="high">สำคัญมาก</option><option value="medium">ปานกลาง</option><option value="low">ไม่เร่ง</option></select></label></div><label>รายละเอียด<textarea value={d.details} onChange={e=>setD({...d,details:e.target.value})}/></label>{err&&<p className="error">{err}</p>}<footer>{task.id&&<button type="button" className="delete" onClick={()=>remove(task.id)}>ลบงาน</button>}<span/><button type="button" onClick={close}>ยกเลิก</button><button className="primary">บันทึกงาน</button></footer></form></div>}
